# Generated by Django 2.2.5 on 2020-02-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0022_collaborativeworkspaceeditortype_editingeventtype'),
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborative_workspace_editor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jargon.CollaborativeWorkspaceEditorType')),
                ('editing_event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jargon.EditingEventType')),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_metadata', to='reversion.Revision')),
            ],
        ),
    ]
