# Generated by Django 2.0.9 on 2018-10-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='revisionmetadata',
            name='editor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archival.EditorType'),
        ),
    ]
