# Generated by Django 2.0.9 on 2018-10-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0003_add_fields_cataloguer_and_description_date_to_collection_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creators',
            field=models.ManyToManyField(related_name='files_created', to='archival.Person'),
        ),
        migrations.AddField(
            model_name='item',
            name='creators',
            field=models.ManyToManyField(related_name='items_created', to='archival.Person'),
        ),
    ]
