# Generated by Django 2.0.9 on 2018-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0004_add_field_creators_to_file_and_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creation_places',
            field=models.ManyToManyField(related_name='items_created', to='archival.Place'),
        ),
    ]
