# Generated by Django 2.0.9 on 2018-10-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0005_item_creation_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archival.Collection'),
        ),
        migrations.AlterField(
            model_name='series',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archival.Series'),
        ),
    ]
