# Generated by Django 2.0.9 on 2018-10-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0006_add_field_collection_to_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archival.Series'),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archival.File'),
        ),
    ]
