# Generated by Django 2.0.9 on 2018-10-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0007_add_field_series_to_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archival.File', verbose_name='File'),
        ),
    ]
