# Generated by Django 2.0.9 on 2018-10-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0008_item_f'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationstatus',
            options={'verbose_name_plural': 'Publication status'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='language',
            new_name='languages',
        ),
    ]
