# Generated by Django 2.0.9 on 2018-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0009_renamed_field_language_to_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='title',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='title',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
