# Generated by Django 2.0.9 on 2018-10-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('archival', '0011_removed_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='languages',
            field=models.ManyToManyField(to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='file',
            name='languages',
            field=models.ManyToManyField(to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='item',
            name='languages',
            field=models.ManyToManyField(to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='series',
            name='languages',
            field=models.ManyToManyField(to='languages_plus.Language'),
        ),
    ]
