# Generated by Django 2.0.9 on 2018-10-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0012_languages_plus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='organisations',
            new_name='organisations_as_subjects',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='persons',
            new_name='persons_as_subjects',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='places',
            new_name='places_as_subjects',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='organisations',
            new_name='organisations_as_subjects',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='persons',
            new_name='persons_as_subjects',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='places',
            new_name='places_as_subjects',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='organisations',
            new_name='organisations_as_subjects',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='persons',
            new_name='persons_as_subjects',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='places',
            new_name='places_as_subjects',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='organisations',
            new_name='organisations_as_subjects',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='persons',
            new_name='persons_as_subjects',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='places',
            new_name='places_as_subjects',
        ),
    ]
