# Generated by Django 2.0.9 on 2018-10-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0013_rename_subject_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='persons_as_relations',
            field=models.ManyToManyField(related_name='files_as_relations', to='archival.Person'),
        ),
        migrations.AddField(
            model_name='item',
            name='persons_as_relations',
            field=models.ManyToManyField(related_name='items_as_relations', to='archival.Person'),
        ),
    ]
