# Generated by Django 2.0.9 on 2018-10-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0014_persons_as_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='places_as_relations',
            field=models.ManyToManyField(related_name='files_as_relations', to='archival.Place'),
        ),
        migrations.AddField(
            model_name='item',
            name='places_as_relations',
            field=models.ManyToManyField(related_name='items_as_relations', to='archival.Place'),
        ),
    ]
