# Generated by Django 2.0.9 on 2018-10-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0015_places_as_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creation_dates',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='extent',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='collection',
            name='related_materials',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='copyright_status',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='creation_dates',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='extent',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='related_materials',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='whithheld',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='copyright_status',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='creation_dates',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='extent',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='related_materials',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='whithheld',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='creation_dates',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='extent',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='series',
            name='related_materials',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
