# Generated by Django 2.0.9 on 2018-11-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0016_convert_textfields_to_charfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionmetadata',
            name='editor_type',
        ),
        migrations.RemoveField(
            model_name='revisionmetadata',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='revisionmetadata',
            name='revision',
        ),
        migrations.DeleteModel(
            name='EditorType',
        ),
        migrations.DeleteModel(
            name='RevisionEvent',
        ),
        migrations.DeleteModel(
            name='RevisionMetadata',
        ),
    ]
