# Generated by Django 2.0.9 on 2018-11-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0017_delete_version_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='publication_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jargon.PublicationStatus'),
        ),
        migrations.AlterField(
            model_name='file',
            name='publication_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jargon.PublicationStatus'),
        ),
        migrations.AlterField(
            model_name='item',
            name='publication_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jargon.PublicationStatus'),
        ),
        migrations.AlterField(
            model_name='series',
            name='publication_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jargon.PublicationStatus'),
        ),
        migrations.DeleteModel(
            name='PublicationStatus',
        ),
    ]
