# Generated by Django 2.0.9 on 2018-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0018_delete_model_publicationstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
