# Generated by Django 2.1.3 on 2018-11-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0019_delete_model_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='record_type',
        ),
        migrations.DeleteModel(
            name='RecordType',
        ),
    ]
