# Generated by Django 2.1.3 on 2018-11-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0021_recordtype_from_jargon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='places_as_subjects',
        ),
        migrations.RemoveField(
            model_name='file',
            name='places_as_relations',
        ),
        migrations.RemoveField(
            model_name='file',
            name='places_as_subjects',
        ),
        migrations.RemoveField(
            model_name='item',
            name='creation_places',
        ),
        migrations.RemoveField(
            model_name='item',
            name='places_as_relations',
        ),
        migrations.RemoveField(
            model_name='item',
            name='places_as_subjects',
        ),
        migrations.RemoveField(
            model_name='series',
            name='places_as_subjects',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
