# Generated by Django 2.1.3 on 2018-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('archival', '0022_delete_model_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='places_as_subjects',
            field=models.ManyToManyField(to='geonames_place.Place'),
        ),
        migrations.AddField(
            model_name='file',
            name='places_as_relations',
            field=models.ManyToManyField(related_name='files_as_relations', to='geonames_place.Place'),
        ),
        migrations.AddField(
            model_name='file',
            name='places_as_subjects',
            field=models.ManyToManyField(to='geonames_place.Place'),
        ),
        migrations.AddField(
            model_name='item',
            name='creation_places',
            field=models.ManyToManyField(related_name='items_created', to='geonames_place.Place'),
        ),
        migrations.AddField(
            model_name='item',
            name='places_as_relations',
            field=models.ManyToManyField(related_name='items_as_relations', to='geonames_place.Place'),
        ),
        migrations.AddField(
            model_name='item',
            name='places_as_subjects',
            field=models.ManyToManyField(to='geonames_place.Place'),
        ),
        migrations.AddField(
            model_name='series',
            name='places_as_subjects',
            field=models.ManyToManyField(to='geonames_place.Place'),
        ),
    ]
