# Generated by Django 2.1.3 on 2018-11-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0023_add_place_from_geonames_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='whithheld',
            new_name='withheld',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='whithheld',
            new_name='withheld',
        ),
    ]
