# Generated by Django 2.1.3 on 2018-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0024_fix_field_name_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='persons_as_subjects',
            field=models.ManyToManyField(to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='file',
            name='creators',
            field=models.ManyToManyField(related_name='files_created', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='file',
            name='persons_as_relations',
            field=models.ManyToManyField(related_name='files_as_relations', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='file',
            name='persons_as_subjects',
            field=models.ManyToManyField(to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creators',
            field=models.ManyToManyField(related_name='items_created', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='persons_as_relations',
            field=models.ManyToManyField(related_name='items_as_relations', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='persons_as_subjects',
            field=models.ManyToManyField(to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='series',
            name='persons_as_subjects',
            field=models.ManyToManyField(to='authority.Entity'),
        ),
    ]
