# Generated by Django 2.1.3 on 2018-11-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0025_alter_person_fields_to_entity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
