# Generated by Django 2.1.3 on 2018-12-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0027_add_field_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
