# Generated by Django 2.1.3 on 2018-12-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0028_alter_field_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='repository_code',
        ),
        migrations.RemoveField(
            model_name='file',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='file',
            name='repository_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='item',
            name='repository_code',
        ),
        migrations.RemoveField(
            model_name='series',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='series',
            name='repository_code',
        ),
    ]
