# Generated by Django 2.1.3 on 2018-12-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0014_repository'),
        ('archival', '0029_remove_repository_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='repository',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jargon.Repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='repository',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jargon.Repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='repository',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jargon.Repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='repository',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jargon.Repository'),
            preserve_default=False,
        ),
    ]
