# Generated by Django 2.1.3 on 2018-12-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0030_add_field_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='archival_level',
        ),
        migrations.RemoveField(
            model_name='file',
            name='archival_level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='archival_level',
        ),
        migrations.RemoveField(
            model_name='series',
            name='archival_level',
        ),
    ]
