# Generated by Django 2.1.3 on 2018-12-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0017_referencesource'),
        ('archival', '0031_remove_field_archival_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='title',
        ),
        migrations.AddField(
            model_name='reference',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jargon.ReferenceSource'),
            preserve_default=False,
        ),
    ]
