# Generated by Django 2.1.3 on 2018-12-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0032_remove_field_title_and_add_field_source_to_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creation_dates',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='creation_dates',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='creation_dates',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='creation_dates',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
