# Generated by Django 2.1.3 on 2018-12-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0033_alter_field_creation_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
