# Generated by Django 2.1.4 on 2019-01-09 15:49

from django.db import migrations, models
import django.db.models.deletion


def fill_polymorphic_content_type(apps, schema_editor):
    for m in ['Collection', 'File', 'Item', 'Series']:
        MyModel = apps.get_model('archival', m)
        ContentType = apps.get_model('contenttypes', 'ContentType')

        new_ct = ContentType.objects.get_for_model(MyModel)
        MyModel.objects.filter(polymorphic_ctype__isnull=True).update(
            polymorphic_ctype=new_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('archival', '0035_item_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_archival.collection_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='file',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_archival.file_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='item',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_archival.item_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='series',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_archival.series_set+', to='contenttypes.ContentType'),
        ),

        migrations.RunPython(fill_polymorphic_content_type,
                             migrations.RunPython.noop),
    ]
