# Generated by Django 2.1.4 on 2019-01-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('jargon', '0018_change_meta_options'),
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('authority', '0045_change_meta_options'),
        ('archival', '0036_convert_collectionbase_to_polymorphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('creation_dates', models.CharField(max_length=256)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('extent', models.CharField(max_length=256)),
                ('related_materials', models.CharField(blank=True, max_length=256, null=True)),
                ('cataloguer', models.CharField(max_length=512)),
                ('description_date', models.DateField()),
                ('rights_declaration', models.TextField()),
                ('languages', models.ManyToManyField(to='languages_plus.Language')),
                ('organisations_as_subjects', models.ManyToManyField(to='archival.Organisation')),
                ('persons_as_subjects', models.ManyToManyField(to='authority.Entity')),
                ('places_as_subjects', models.ManyToManyField(to='geonames_place.Place')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_archival.archivalrecord_set+', to='contenttypes.ContentType')),
                ('publication_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jargon.PublicationStatus')),
                ('references', models.ManyToManyField(to='archival.Reference')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jargon.Repository')),
                ('subjects', models.ManyToManyField(to='archival.Subject')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='parent',
            new_name='parent_file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='series',
            new_name='parent_series',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='f',
            new_name='parent_file',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='series',
            new_name='parent_series',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='collection',
            new_name='parent_collection',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='parent',
            new_name='parent_series',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='cataloguer',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='creation_dates',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='extent',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='organisations_as_subjects',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='persons_as_subjects',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='places_as_subjects',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='references',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='related_materials',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='rights_declaration',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='file',
            name='cataloguer',
        ),
        migrations.RemoveField(
            model_name='file',
            name='creation_dates',
        ),
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.RemoveField(
            model_name='file',
            name='description_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='extent',
        ),
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='file',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='file',
            name='organisations_as_subjects',
        ),
        migrations.RemoveField(
            model_name='file',
            name='persons_as_subjects',
        ),
        migrations.RemoveField(
            model_name='file',
            name='places_as_subjects',
        ),
        migrations.RemoveField(
            model_name='file',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='file',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='file',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='file',
            name='references',
        ),
        migrations.RemoveField(
            model_name='file',
            name='related_materials',
        ),
        migrations.RemoveField(
            model_name='file',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='file',
            name='rights_declaration',
        ),
        migrations.RemoveField(
            model_name='file',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cataloguer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='creation_dates',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='extent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='item',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='organisations_as_subjects',
        ),
        migrations.RemoveField(
            model_name='item',
            name='persons_as_subjects',
        ),
        migrations.RemoveField(
            model_name='item',
            name='places_as_subjects',
        ),
        migrations.RemoveField(
            model_name='item',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='item',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='item',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='references',
        ),
        migrations.RemoveField(
            model_name='item',
            name='related_materials',
        ),
        migrations.RemoveField(
            model_name='item',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rights_declaration',
        ),
        migrations.RemoveField(
            model_name='item',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='series',
            name='cataloguer',
        ),
        migrations.RemoveField(
            model_name='series',
            name='creation_dates',
        ),
        migrations.RemoveField(
            model_name='series',
            name='description',
        ),
        migrations.RemoveField(
            model_name='series',
            name='description_date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='extent',
        ),
        migrations.RemoveField(
            model_name='series',
            name='id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='series',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='series',
            name='organisations_as_subjects',
        ),
        migrations.RemoveField(
            model_name='series',
            name='persons_as_subjects',
        ),
        migrations.RemoveField(
            model_name='series',
            name='places_as_subjects',
        ),
        migrations.RemoveField(
            model_name='series',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='series',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='series',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='series',
            name='references',
        ),
        migrations.RemoveField(
            model_name='series',
            name='related_materials',
        ),
        migrations.RemoveField(
            model_name='series',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='series',
            name='rights_declaration',
        ),
        migrations.RemoveField(
            model_name='series',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='series',
            name='title',
        ),
        migrations.RemoveField(
            model_name='series',
            name='uuid',
        ),
        migrations.AddField(
            model_name='collection',
            name='archivalrecord_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archival.ArchivalRecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='archivalrecord_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archival.ArchivalRecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='archivalrecord_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archival.ArchivalRecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='archivalrecord_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archival.ArchivalRecord'),
            preserve_default=False,
        ),
    ]
