# Generated by Django 2.1.5 on 2019-01-14 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archival', '0037_move_to_polymorphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalRecordSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='archivalrecord',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='archivalrecordset',
            name='archival_records',
            field=models.ManyToManyField(to='archival.ArchivalRecord'),
        ),
        migrations.AddField(
            model_name='archivalrecordset',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
