# Generated by Django 2.1.5 on 2019-01-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0038_archivalrecordset'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecordset',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
