# Generated by Django 2.1.5 on 2019-01-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0040_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='images',
            field=models.ManyToManyField(to='archival.Image'),
        ),
    ]
