# Generated by Django 2.1.5 on 2019-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0041_archivalrecord_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mime_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
