# Generated by Django 2.1.5 on 2019-01-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0042_image_mime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalrecord',
            name='images',
        ),
    ]
