# Generated by Django 2.1.5 on 2019-01-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0043_remove_archivalrecord_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
