# Generated by Django 2.1.5 on 2019-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('archival', '0044_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='media',
            field=models.ManyToManyField(to='media.Media'),
        ),
    ]
