# Generated by Django 2.1.7 on 2019-04-26 10:35

from django.conf import settings
from django.db import migrations


def add_rights_declaration(apps, schema_editor):
    ArchivalRecord = apps.get_model('archival', 'ArchivalRecord')

    for ar in ArchivalRecord.objects.all():
        if not ar.rights_declaration:
            ar.rights_declaration = settings.ARCHIVAL_RIGHTS_DECLARATION
            ar.save()


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0046_alter_field_rights_declaration_on_archivalrecord'),
    ]

    operations = [
        migrations.RunPython(add_rights_declaration,
                             reverse_code=migrations.RunPython.noop)
    ]
