# Generated by Django 2.1.7 on 2019-04-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0048_alter_field_rights_declaration_on_archivalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='files_created', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='file',
            name='persons_as_relations',
            field=models.ManyToManyField(blank=True, related_name='files_as_relations', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='file',
            name='places_as_relations',
            field=models.ManyToManyField(blank=True, related_name='files_as_relations', to='geonames_place.Place'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='items_created', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='persons_as_relations',
            field=models.ManyToManyField(blank=True, related_name='items_as_relations', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='places_as_relations',
            field=models.ManyToManyField(blank=True, related_name='items_as_relations', to='geonames_place.Place'),
        ),
    ]
