# Generated by Django 2.1.7 on 2019-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0049_alter_creators_and_relations_on_file_and_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='media',
            field=models.ManyToManyField(blank=True, to='media.Media'),
        ),
    ]
