# Generated by Django 2.1.7 on 2019-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0050_alter_field_media_on_archivalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='organisations_as_subjects',
            field=models.ManyToManyField(blank=True, to='archival.Organisation'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='persons_as_subjects',
            field=models.ManyToManyField(blank=True, to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='places_as_subjects',
            field=models.ManyToManyField(blank=True, to='geonames_place.Place'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='archival.Subject'),
        ),
    ]
