# Generated by Django 2.1.7 on 2019-04-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0051_alter_subject_fields_on_archivalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='copyright_status',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='copyright_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
