# Generated by Django 2.1.7 on 2019-04-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0052_alter_field_copyright_status_on_file_and_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creation_places',
            field=models.ManyToManyField(blank=True, related_name='items_created', to='geonames_place.Place'),
        ),
    ]
