# Generated by Django 2.1.7 on 2019-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('archival', '0053_creation_places_allow_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creation_places',
            field=models.ManyToManyField(blank=True, related_name='files_created', to='geonames_place.Place'),
        ),
    ]
