# Generated by Django 2.1.7 on 2019-06-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0055_add_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='project',
            field=models.ForeignKey(help_text='Which project does this record                                    belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archival.Project'),
        ),
        migrations.AddField(
            model_name='archivalrecordset',
            name='project',
            field=models.ForeignKey(help_text='Which project does this set                                    belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archival.Project'),
        ),
    ]
