# Generated by Django 2.1.7 on 2019-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0056_add_project_fk_to_arch_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
