# Generated by Django 2.1.7 on 2019-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0057_add_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='creation_dates',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='extent',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='related_materials',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
