# Generated by Django 2.1.7 on 2019-07-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0058_increase_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='aquisition_dates',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='aquisition_dates_notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='connection_a',
            field=models.CharField(blank=True, help_text='Generic Connection Text A', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='connection_b',
            field=models.CharField(blank=True, help_text='Generic Connection Text B', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='connection_c',
            field=models.CharField(blank=True, help_text='Generic Connection Text C', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='creation_dates_notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='origin_location',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='physical_location',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='publication_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='cataloguer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='creation_dates',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='extent',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='languages',
            field=models.ManyToManyField(blank=True, to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='references',
            field=models.ManyToManyField(blank=True, to='archival.Reference'),
        ),
    ]
