# Generated by Django 2.1.7 on 2019-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0059_squashed_sharc_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='rcin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
