# Generated by Django 2.1.7 on 2019-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0065_relation changes'),
        ('archival', '0060_archivalrecord_rcin'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='related_entities',
            field=models.ManyToManyField(blank=True, related_name='related_entities', to='authority.Entity'),
        ),
    ]
