# Generated by Django 2.2.6 on 2019-10-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0061_related_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='creation_dates',
            field=models.CharField(blank=True, help_text="This element identifies and records the date(s) of creation of the records being described. The bulk of the records are within a certain period with only a few records of earlier or later date. In the latter case, if significant, reference should be made in the Description field In the case of double-dating, the new style of date should be entered in the Date field. Add both the new style and old style of date in the Description field Square brackets should be used for derived dates. If there is any doubt as to the precise date, it can be preceded by &quot;?&quot; if the exact date is questionable or &quot;c.&quot;; if you are only able to narrow down the date range of the document by research. Some approximation of date should always be possible from the record's relationship to other records in the series, office holders named, external events referred to, etc. The use of n.d. for undated should be avoided. If a document is undated, this can be noted in the Description field.", max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='end_date',
            field=models.DateField(blank=True, help_text='This element is used to identify the end date of the document(s). For Collection and Series levels, year dates should be used. For Sub-Series level and below, dates should include day and month (if known). Some approximation of date should always be possible from the record-relationship to other records in the series, office holders named, external events referred to, etc. This data element is for machine-reading and should be replicated in the Date (free-text) data element. No letters, symbols or characters other than numbers should be entered.', null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='references',
            field=models.ManyToManyField(blank=True, help_text='This element is used for the Royal Archive, former and CALM references.', to='archival.Reference'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='repository',
            field=models.ForeignKey(help_text='This element is used to give the managing custodian of the material being described. &quot;Royal Archives&quot; is the default content. Choose &quot;Royal Library&quot; when necessary.', on_delete=django.db.models.deletion.CASCADE, to='jargon.Repository'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='start_date',
            field=models.DateField(blank=True, help_text='This element is used to identify the start date of the document(s). For Collection and Series levels, year dates should be used. For Sub-Series level and below, dates should include day and month (if known). Some approximation of date should always be possible from the record-relationship to other records in the series, office holders named, external events referred to, etc. This data element is for machine-reading and should be replicated in the Date (free-text) data element. No letters, symbols or characters other than numbers should be entered.', null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='title',
            field=models.CharField(help_text='This element is used to provide the name of the document(s) appropriate to the level of description. The title should normally not be longer than one sentence in length. If it is possible to summarise the whole document in the Title field then do so and omit use of the Description field. Dates should not normally be included in the Title field unless integral to the name of the record in question. At collection and series level, titles should provide a concise summary of the scope and content of the papers being described. In the case of letters, give the name of the writer and addressee. For those letters with a very clear sense of subject, this can be referred to briefly in the Title field. For those letters with a less clear subject (usually personal family letters which are very hard to summarise), the broad description &quot;on family matters&quot; should be used.', max_length=1024),
        ),
    ]
