# Generated by Django 2.2.6 on 2019-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0062_auto_20191015_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='origin_location',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='location of originals'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='rcin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='RCIN'),
        ),
    ]
