# Generated by Django 2.2.7 on 2019-11-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0063_auto_20191022_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='provenance',
            field=models.TextField(blank=True, null=True, verbose_name='Custodial History/Provenance'),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
