# Generated by Django 2.2.7 on 2019-11-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0064_auto_20191114_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='creation_dates',
            field=models.CharField(blank=True, help_text='This element identifies and records the date(s) of creation of the records being described. The bulk of the records are within a certain period with only a few records of earlier or later date. In the latter case, if significant, reference should be made in the Description field. In the case of double-dating, the new style of date should be entered in the Date field. Add both the new style and old style of date in the Description field Square brackets should be used for derived dates. If there is any doubt as to the precise date, it can be preceded by &quot;?&quot; if the exact date is questionable or &quot;c.&quot;; if you are only able to narrow down the date range of the document by research. Some approximation of date should always be possible from the record relationship to other records in the series, office holders named, external events referred to, etc. The use of n.d. for undated should be avoided. If a document is undated, this can be noted in the Description field.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='description',
            field=models.TextField(blank=True, help_text='This element is used to give a concise statement that describes the scope and content of the document(s), in particular what the material is and what it relates to. This should be a summary of the content of the document(s) appropriate and relevant to the level of description. This data element should include any issues with dates that cannot be expressed in the Dates field. For higher level records, metadata in the Description field can be itemised to reflect the content of the lower levels of the hierarchy. Content included in the Title field should not be repeated in the Description field. Thought should be given to subject keywords (people, places, events and topics) when entering the Description metadata. Quotations from the document(s) are acceptable in moderation, particularly if it is the only way to summarise the content of a document. Long transcripts should not be included. Record if a document is a copy or a draft or signed or unsigned in this data element. The time the document was signed can also be entered in the Description field. Any decorations, drawings or sketcheson the document can be noted here. Include cross-references to other documents in the collection in this field, for example when referring to enclosures and replies.', null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='extent',
            field=models.CharField(help_text='This element is used to give the number of records at the level being described. The extent of the record(s) should be given as appropriate to the level of description. This gives the user an idea of the size of a collection, series, item or file they are interested in. At higher levels, boxes can be included to help users visualise the size of the collection. At file and item levels, number of pages in the document(s) are required (in brackets) in order to guide users as to the size of the digital image download (PDF format). This should be ascertained at the cataloguing stage and not from the PDF. One letter equals one document regardless of length.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='This element is used to give the language(s) in which the documents are written. English is the default content for this field. A new Language field should be created for each language entered. Prominence should be reflected, with the most heavily-used language being given first. At collection and series level the Language data element should give an indication of the most prominent language rather than every single language.', to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='This element is used to accommodate specialised information that cannot be entered in another data element. This field should only be used if there is information about the document(s) that cannot be accommodated in any of the other data elements.', null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='origin_location',
            field=models.CharField(blank=True, help_text='This element is used to indicate the existence and location, availability and/or destruction of originals, if the unit of description consists of copies. If the original of the unit of description is available (either in the RA or elsewhere), its location should be recorded, together with any significant references. If the originals no longer exist, or their location is unknown, give that information.', max_length=2048, null=True, verbose_name='location of originals'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='provenance',
            field=models.TextField(blank=True, help_text='This element is used to give information about the stewardship of papers prior to their accession to the Royal Archives. This data element should be used at whatever level it is appropriate to record custodial history information. Information on custodial history can often be found in the relevant accession record, but it is not always possible to ascertain how a collection entered the Royal Archives. If it is possible to ascertain that the collection entered the Royal Archives with the main deposit from Apsley House, this should be recorded. The name of donor and circumstances of the accession can be given, however it is not necessary to record the cost of the accession (at auction or otherwise). Information about Royal Household departments which reflect or affect the custodial history of the papers should also be included.', null=True, verbose_name='Custodial History/Provenance'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='related_materials',
            field=models.CharField(blank=True, help_text='This element is used for the cross-referencing of relevant material held elsewhere in the Georgian Papers.', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='archivalrecordset',
            name='title',
            field=models.CharField(help_text='This element is used to provide the name of the document(s) appropriate to the level of description. The title should normally not be longer than one sentence in length. If it is possible to summarise the whole document in the Title field then do so and omit use of the Description field. Dates should not normally be included in the Title field unless integral to the name of the record in question. At collection and series level, titles should provide a concise summary of the scope and content of the papers being described. In the case of letters, give the name of the writer and addressee. For those letters with a very clear sense of subject, this can be referred to briefly in the Title field. For those letters with a less clear subject (usually personal family letters which are very hard to summarise), the broad description &quot;on family matters&quot; should be used.', max_length=256),
        ),
        migrations.AlterField(
            model_name='collection',
            name='administrative_history',
            field=models.TextField(help_text='This element is used to give the administrative history, biographical details or other historical information about the individual(s) or administrative body/bodies responsible for creating and accumulating the records being described. In the case of individuals, the Administrative History should include full names and titles, the life dates of the person, significant achievements and an outline of their career, concentrating on the period covered by the records in the series. The records of few administrative bodies are included in the Georgian Papers, but for those that are a summary of the organisation (or department) should include its title, purpose and function, and dates of existence as appropriate. It should be noted that the collections within the Georgian Papers are predominately artificial in creation and are based on records to, from and about an individual, rather than being records created by an individual. Some collections are also gathered together by type, and this should be reflected in the Administrative History. This data element should not be used for information about custodial history. Information entered in this data element should be pertinent to the creation of the particular collection of papers.'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='arrangement',
            field=models.TextField(help_text='This element is used to provide information on the internal structure, order and/or system of classification of the unit of description. If the existing order of the papers has been preserved in cataloguing, this should be reflected in this data element. Re-arrangement of documents in the Georgian Papers is infrequent, but this data element should also be used to note any such re-arrangement or noteworthy points about the existing arrangement. At the top-level, a statement to note that "this collection has been artificially created as part of the Georgian Papers digitisation and cataloguing programme" should be included.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='copyright_status',
            field=models.CharField(blank=True, help_text='This is an administrative field in which the copyright status of a document is given in order to inform the copyright clearance process for publication. This field should be completed at the level at which the digitised document is attached. It should be completed in conjunction with the internal document &quot;Guide to Copyright Categories&quot; for guidance as to which  option to choose from the picklist.', max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='creation_places',
            field=models.ManyToManyField(blank=True, help_text='The place of writing should be given whether it is a town, house, palace, ship, public house, etc. Enter what is given on the document, do not add details of the town etc. if they are not expressed in the document.', related_name='files_created', to='geonames_place.Place'),
        ),
        migrations.AlterField(
            model_name='file',
            name='creators',
            field=models.ManyToManyField(blank=True, help_text='This element is entered when the writer of the document can be identified. The name and title of the writer at the time of writing should be given. This data element will generally be used at File and Item level, but sometimes at Series level if the whole group of papers has been written by the same individual. If the writer cannot be identified, this data element should be left blank. Writers are those who own the intellectual content of a document, not the copyist. If the document has more than one writer, a new Writer field should be created for each name. Include life dates (in form 1765-1837) when necessary to differentiate between members of the royal family with the same name and title. Job title or occupation can be included if considered necessary, but is not mandatory. It is particularly useful for members of the Royal Household and tradespeople. Names and job titles should be separated by a semi-colon.', related_name='files_created', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='file',
            name='physical_description',
            field=models.TextField(blank=True, help_text='This element is used to describe the physical appearance of the document(s) and/or carriers, to aid visualisation by the user. Enter at the level at which the digitised image is attached. Provide a brief description of the physical attributes of the document(s) to help users visualise the original when viewing the digitised version.', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='publication_permission',
            field=models.TextField(blank=True, null=True, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='file',
            name='publications',
            field=models.ManyToManyField(help_text='This element is used to identify any publications that are about or are based on the use or study of the document(s) in question. It is used to record a citation to, and/or information about, a publication that is about or based on the use or study of the unit of description, particularly transcriptions and references to published facsimiles. For the purposes of the Georgian Papers, this will predominately be the volumes edited by Aspinall, Fortescue, Namier and Donne.', to='jargon.Publication'),
        ),
        migrations.AlterField(
            model_name='file',
            name='record_type',
            field=models.ManyToManyField(help_text='This element is used to distinguish different types of record to enable users to filter searches to specific types of documents. This data element should be completed at the lowest level possible.', to='jargon.RecordType'),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, help_text='This element is used to give the file name of the digitised image of the document(s) (PDF) to enable users to link to Georgian Papers Online from shared catalogue data.', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='file',
            name='withheld',
            field=models.CharField(blank=True, help_text='This element is used to state when the digital image of a document(s) has been withheld from publication for copyright, conservation or other reasons. This field should be completed when the digital image of a document(s) cannot be published on Georgian Papers Online because copyright clearance has not been established or the document is too fragile to be digitised. It should be completed at the level at which the image should have been attached. This data element will typically be completed by the GPP Content Delivery Project Manager or the Archivist (Digital). If an item is missing, note in this data element.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='copyright_status',
            field=models.CharField(blank=True, help_text='This is an administrative field in which the copyright status of a document is given in order to inform the copyright clearance process for publication. This field should be completed at the level at which the digitised document is attached. It should be completed in conjunction with the internal document &quot;Guide to Copyright Categories&quot; for guidance as to which  option to choose from the picklist.', max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='physical_description',
            field=models.TextField(blank=True, help_text='This element is used to describe the physical appearance of the document(s) and/or carriers, to aid visualisation by the user. Enter at the level at which the digitised image is attached. Provide a brief description of the physical attributes of the document(s) to help users visualise the original when viewing the digitised version.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='publication_permission',
            field=models.TextField(blank=True, null=True, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='publications',
            field=models.ManyToManyField(help_text='This element is used to identify any publications that are about or are based on the use or study of the document(s) in question. It is used to record a citation to, and/or information about, a publication that is about or based on the use or study of the unit of description, particularly transcriptions and references to published facsimiles. For the purposes of the Georgian Papers, this will predominately be the volumes edited by Aspinall, Fortescue, Namier and Donne.', to='jargon.Publication'),
        ),
        migrations.AlterField(
            model_name='item',
            name='record_type',
            field=models.ManyToManyField(help_text='This element is used to distinguish different types of record to enable users to filter searches to specific types of documents. This data element should be completed at the lowest level possible.', to='jargon.RecordType'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, help_text='This element is used to give the file name of the digitised image of the document(s) (PDF) to enable users to link to Georgian Papers Online from shared catalogue data.', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='withheld',
            field=models.CharField(blank=True, help_text='This element is used to state when the digital image of a document(s) has been withheld from publication for copyright, conservation or other reasons. This field should be completed when the digital image of a document(s) cannot be published on Georgian Papers Online because copyright clearance has not been established or the document is too fragile to be digitised. It should be completed at the level at which the image should have been attached. This data element will typically be completed by the GPP Content Delivery Project Manager or the Archivist (Digital). If an item is missing, note in this data element.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='arrangement',
            field=models.TextField(help_text='This element is used to provide information on the internal structure, order and/or system of classification of the unit of description. If the existing order of the papers has been preserved in cataloguing, this should be reflected in this data element. Re-arrangement of documents in the Georgian Papers is infrequent, but this data element should also be used to note any such re-arrangement or noteworthy points about the existing arrangement. At the top-level, a statement to note that "this collection has been artificially created as part of the Georgian Papers digitisation and cataloguing programme" should be included.'),
        ),
        migrations.AlterField(
            model_name='series',
            name='publications',
            field=models.ManyToManyField(help_text='This element is used to identify any publications that are about or are based on the use or study of the document(s) in question. It is used to record a citation to, and/or information about, a publication that is about or based on the use or study of the unit of description, particularly transcriptions and references to published facsimiles. For the purposes of the Georgian Papers, this will predominately be the volumes edited by Aspinall, Fortescue, Namier and Donne.', to='jargon.Publication'),
        ),
    ]
