# Generated by Django 2.2.5 on 2020-02-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0068_auto_20200220_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecordset',
            name='project',
            field=models.ForeignKey(help_text='Which project does this set belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archival.Project'),
        ),
    ]
