# Generated by Django 2.2.5 on 2020-03-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0069_auto_20200220_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ArchivalRecordImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ar_transcription_images/')),
                ('order', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival.ArchivalRecord')),
            ],
            options={
                'unique_together': {('record', 'order')},
            },
        ),
    ]
