# Generated by Django 2.2.5 on 2020-03-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0070_auto_20200301_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecordimage',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_images', to='archival.ArchivalRecord'),
        ),
    ]
