# Generated by Django 2.2.10 on 2020-03-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0071_auto_20200301_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivalrecordimage',
            options={'ordering': ['order']},
        ),
    ]
