# Generated by Django 2.2.10 on 2020-03-04 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0072_auto_20200303_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Which project does this record belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archival.Project'),
        ),
    ]
