# Generated by Django 2.2.5 on 2020-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0073_auto_20200304_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
