# Generated by Django 2.2.5 on 2020-03-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0074_archivalrecord_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='record_subjects', to='jargon.Function'),
        ),
    ]
