# Generated by Django 2.2.5 on 2020-03-23 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script_codes', '0003_change_meta_options_on_script'),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('archival', '0075_auto_20200319_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.PROTECT, related_name='record_control_languages', to='languages_plus.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='script',
            field=models.ForeignKey(default=82, on_delete=django.db.models.deletion.PROTECT, related_name='record_control_scripts', to='script_codes.Script'),
            preserve_default=False,
        ),
    ]
