# Generated by Django 2.2.5 on 2020-03-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0076_auto_20200323_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalrecord',
            name='is_deleted',
        ),
    ]
