# Generated by Django 2.2.12 on 2020-04-28 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0077_remove_archivalrecord_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalRecordTranscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_texts', to='archival.ArchivalRecord')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('record', 'order')},
            },
        ),
    ]
