# Generated by Django 2.2.12 on 2020-05-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0078_archivalrecordtranscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecordtranscription',
            name='corrector',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='archivalrecordtranscription',
            name='reviewer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='archivalrecordtranscription',
            name='transcriber',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='collection',
            name='arrangement',
            field=models.TextField(help_text='This element is used to provide information on the internal structure, order and/or system of classification of the unit of description. If the existing order of the papers has been preserved in cataloguing, this should be reflected in this data element. Re-arrangement of documents in the Georgian Papers is infrequent, but this data element should also be used to note any such re-arrangement or noteworthy points about the existing arrangement. At the top-level, a statement to note that &quot;this collection has been artificially created as part of the Georgian Papers digitisation and cataloguing programme&quot; should be included.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, help_text='This element is used to hold the URLs for the archival record in the Georgian Papers Online website, https://gpp.rct.uk/.', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, help_text='This element is used to hold the URLs for the archival record in the Georgian Papers Online website, https://gpp.rct.uk/.', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='series',
            name='arrangement',
            field=models.TextField(help_text='This element is used to provide information on the internal structure, order and/or system of classification of the unit of description. If the existing order of the papers has been preserved in cataloguing, this should be reflected in this data element. Re-arrangement of documents in the Georgian Papers is infrequent, but this data element should also be used to note any such re-arrangement or noteworthy points about the existing arrangement. At the top-level, a statement to note that &quot;this collection has been artificially created as part of the Georgian Papers digitisation and cataloguing programme&quot; should be included.'),
        ),
    ]
