# Generated by Django 2.2.12 on 2020-05-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0079_auto_20200508_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalrecord',
            name='transcription',
        ),
    ]
