# Generated by Django 2.2.12 on 2020-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0081_auto_20200515_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='organisations_as_subjects',
            field=models.ManyToManyField(blank=True, to='archival.Organisation', verbose_name='Corporate bodies as subjects'),
        ),
        migrations.AlterField(
            model_name='originlocation',
            name='location',
            field=models.CharField(help_text='This element is used to indicate the existence and location, availability and/or destruction of originals, if the unit of description consists of copies. If the original of the unit of description is available (either in the RA or elsewhere), its location should be recorded, together with any significant references. If the originals no longer exist, or their location is unknown, give that information.', max_length=256, verbose_name='location of originals'),
        ),
    ]
