# Generated by Django 2.2.12 on 2020-05-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0082_auto_20200518_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creation_places',
            field=models.ManyToManyField(blank=True, help_text='If the place of writing/receiving address is not available in the Geonames search, please include specific details in the record description.', related_name='files_created', to='geonames_place.Place', verbose_name='Place of writing'),
        ),
        migrations.AlterField(
            model_name='file',
            name='publication_permission',
            field=models.TextField(blank=True, help_text='This element is used to credit copyright holders who have given permission for material to be published online and require public acknowledgment. It should be completed when copyright holders have specifically requested a credit on Georgian Papers Online. it should also be completed at the level at which the image is attached. This data element will typically be completed by the GPP Content Delivery Project Manager or the Archivist (Digital) at the Royal Archives.', null=True, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='publication_permission',
            field=models.TextField(blank=True, help_text='This element is used to credit copyright holders who have given permission for material to be published online and require public acknowledgment. It should be completed when copyright holders have specifically requested a credit on Georgian Papers Online. it should also be completed at the level at which the image is attached. This data element will typically be completed by the GPP Content Delivery Project Manager or the Archivist (Digital) at the Royal Archives.', null=True, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='originlocation',
            name='location',
            field=models.CharField(blank=True, help_text='This element is used to indicate the existence and location, availability and/or destruction of originals, if the unit of description consists of copies. If the original of the unit of description is available (either in the RA or elsewhere), its location should be recorded, together with any significant references. If the originals no longer exist, or their location is unknown, give that information.', max_length=256, verbose_name='location of originals'),
        ),
    ]
