# Generated by Django 2.2.12 on 2020-05-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0083_auto_20200521_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='places_as_relations',
            field=models.ManyToManyField(blank=True, help_text='If the place of writing/receiving address is not available in the Geonames search, please include specific details in the record description.', related_name='files_as_relations', to='geonames_place.Place', verbose_name='Receiving address'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creation_places',
            field=models.ManyToManyField(blank=True, help_text='If the place of writing/receiving address is not available in the Geonames search, please include specific details in the record description.', related_name='items_created', to='geonames_place.Place', verbose_name='Place of writing'),
        ),
        migrations.AlterField(
            model_name='item',
            name='places_as_relations',
            field=models.ManyToManyField(blank=True, help_text='If the place of writing/receiving address is not available in the Geonames search, please include specific details in the record description.', related_name='items_as_relations', to='geonames_place.Place', verbose_name='Receiving address'),
        ),
    ]
