# Generated by Django 2.2.12 on 2020-05-29 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0084_auto_20200526_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_control_languages', to='languages_plus.Language', verbose_name='Record language'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_control_scripts', to='script_codes.Script', verbose_name='Record script'),
        ),
    ]
