# Generated by Django 2.2.12 on 2020-06-04 23:20

import authority.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0086_auto_20200604_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='end_date_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='This element is used to identify the end date of the document(s). For Collection and Series levels, year dates should be used. For Sub-Series level and below, dates should include day and month (if known). Some approximation of date should always be possible from the record-relationship to other records in the series, office holders named, external events referred to, etc. This data element is for machine-reading and should be replicated in the Date (free-text) data element. No letters, symbols or characters other than numbers should be entered.'),
        ),
        migrations.AddField(
            model_name='archivalrecord',
            name='start_date_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='This element is used to identify the start date of the document(s). For Collection and Series levels, year dates should be used. For Sub-Series level and below, dates should include day and month (if known). Some approximation of date should always be possible from the record-relationship to other records in the series, office holders named, external events referred to, etc. This data element is for machine-reading and should be replicated in the Date (free-text) data element. No letters, symbols or characters other than numbers should be entered.'),
        ),
    ]
