# Generated by Django 2.2.12 on 2020-06-04 23:21

from django.db import migrations


def date_to_iso_string(apps, schema_editor):
    # We can't import the models directly as each may be a newer
    # version than this migration expects. We use the historical
    # version.
    ArchivalRecord = apps.get_model('archival', 'ArchivalRecord')
    for record in ArchivalRecord.objects.all():
        if record.start_date:
            record.start_date_partial = record.start_date.isoformat()
        if record.end_date:
            record.end_date_partial = record.end_date.isoformat()
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0087_auto_20200605_0020'),
    ]

    operations = [
        migrations.RunPython(date_to_iso_string),
    ]
