# Generated by Django 2.2.12 on 2020-06-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0088_date_field_to_date_field_partial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalrecord',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='archivalrecord',
            name='start_date',
        ),
    ]
