# Generated by Django 2.2.12 on 2020-06-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0089_auto_20200605_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivalrecord',
            old_name='end_date_partial',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='archivalrecord',
            old_name='start_date_partial',
            new_name='start_date',
        ),
    ]
