# Generated by Django 2.2.12 on 2020-06-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0090_auto_20200605_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='description_date_text',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
