# Generated by Django 2.2.12 on 2020-06-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0092_description_date_to_text_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalrecord',
            name='description_date',
        ),
    ]
