# Generated by Django 2.2.12 on 2020-06-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0093_remove_archivalrecord_description_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivalrecord',
            old_name='description_date_text',
            new_name='description_date',
        ),
    ]
