# Generated by Django 2.2.12 on 2020-06-15 16:14

import authority.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0095_auto_20200614_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='end_date',
            field=authority.fields.PartialDateField(blank=True, help_text='This element is used to identify the end date of the document(s). or Collection and Series levels, year dates should be used. For Sub-Series level and below, dates should include day and month (if known). Some approximation of date should always be possible from the record-relationship to other records in the series, office holders named, external events referred to, etc. This data element is for machine-reading and should be replicated in the Date (free-text) data element. No letters, symbols or characters other than numbers should be entered. To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='start_date',
            field=authority.fields.PartialDateField(help_text='This element is used to identify the start date of the document(s). For Collection and Series levels, year dates should be used. For Sub-Series level and below, dates should include day and month (if known). Some approximation of date should always be possible from the record-relationship to other records in the series, office holders named, external events referred to, etc. This data element is for machine-reading and should be replicated in the Date (free-text) data element. No letters, symbols or characters other than numbers should be entered. To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
    ]
