# Generated by Django 2.2.12 on 2020-06-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0097_auto_20200616_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='publications',
        ),
        migrations.AddField(
            model_name='file',
            name='publications',
            field=models.TextField(blank=True, help_text='This element is used to identify any publications that are about or are based on the use or study of the document(s) in question. It is used to record a citation to, and/or information about, a publication that is about or based on the use or study of the unit of description, particularly transcriptions and references to published facsimiles. For the purposes of the Georgian Papers, this will predominately be the volumes edited by Aspinall, Fortescue, Namier and Donne.', verbose_name='Known previous publications'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='publications',
        ),
        migrations.AddField(
            model_name='item',
            name='publications',
            field=models.TextField(blank=True, help_text='This element is used to identify any publications that are about or are based on the use or study of the document(s) in question. It is used to record a citation to, and/or information about, a publication that is about or based on the use or study of the unit of description, particularly transcriptions and references to published facsimiles. For the purposes of the Georgian Papers, this will predominately be the volumes edited by Aspinall, Fortescue, Namier and Donne.', verbose_name='Known previous publications'),
        ),
        migrations.RemoveField(
            model_name='series',
            name='publications',
        ),
        migrations.AddField(
            model_name='series',
            name='publications',
            field=models.TextField(blank=True, help_text='This element is used to identify any publications that are about or are based on the use or study of the document(s) in question. It is used to record a citation to, and/or information about, a publication that is about or based on the use or study of the unit of description, particularly transcriptions and references to published facsimiles. For the purposes of the Georgian Papers, this will predominately be the volumes edited by Aspinall, Fortescue, Namier and Donne.', verbose_name='Known previous publications'),
        ),
    ]
