# Generated by Django 2.2.12 on 2020-06-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0098_auto_20200616_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='unitid',
            field=models.CharField(max_length=512),
        ),
    ]
