# Generated by Django 2.2.12 on 2020-06-18 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0099_auto_20200617_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmaterialreference',
            name='context',
            field=models.CharField(blank=True, help_text='This element is used for the cross-referencing of relevant material held elsewhere in the Georgian Papers. Please include a descriptive label for the cross-referencing, e.g., &quot;For additional papers relating to Nathaniel Kent, see GEO/ADD/15/0356-0429&quot;', max_length=2048, verbose_name='Related material label'),
        ),
        migrations.AlterField(
            model_name='relatedmaterialreference',
            name='related_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_related_materials', to='archival.ArchivalRecord', verbose_name='Related material'),
        ),
    ]
