# Generated by Django 2.2.12 on 2020-06-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0100_auto_20200618_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='copyright_status',
            field=models.CharField(blank=True, help_text='This is an administrative field in which the copyright status of a document is given in order to inform the copyright clearance process for publication. This field should be completed at the level at which the digitised document is attached. It should be completed in conjunction with the internal document &quot;Guide to Copyright Categories&quot; for guidance as to which  option to choose from the picklist.', max_length=256, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='item',
            name='copyright_status',
            field=models.CharField(blank=True, help_text='This is an administrative field in which the copyright status of a document is given in order to inform the copyright clearance process for publication. This field should be completed at the level at which the digitised document is attached. It should be completed in conjunction with the internal document &quot;Guide to Copyright Categories&quot; for guidance as to which  option to choose from the picklist.', max_length=256, verbose_name='Copyright'),
        ),
    ]
