# Generated by Django 2.2.13 on 2020-06-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0101_updated_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmaterialreference',
            name='context',
            field=models.CharField(help_text='This element is used for the cross-referencing of relevant material held elsewhere in the Georgian Papers. Please include a descriptive label for the cross-referencing, e.g., &quot;For additional papers relating to Nathaniel Kent, see GEO/ADD/15/0356-0429&quot;', max_length=2048, verbose_name='Related material label'),  # noqa
        ),
    ]
