# Generated by Django 2.2.12 on 2020-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0102_auto_20200623_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='rcin',
            field=models.CharField(blank=True, help_text='Royal Collection Inventory Number', max_length=256, null=True, verbose_name='RCIN'),
        ),
    ]
