# Generated by Django 2.2.13 on 2020-07-10 03:40

import authority.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0103_auto_20200707_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalrecord',
            name='cataloguer',
        ),
        migrations.RemoveField(
            model_name='archivalrecord',
            name='description_date',
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='end_date',
            field=authority.fields.PartialDateField(blank=True, help_text='This element is used to identify the end date of the document(s). For Collection and Series levels, year dates should be used. For Sub-Series level and below, dates should include day and month (if known). Some approximation of date should always be possible from the record-relationship to other records in the series, office holders named, external events referred to, etc. <br><br>1. It is required that you follow the date format: <br><strong>(-)YYYY(-MM(-DD))</strong><br><em>e.g., 1822-03-27, 1822-03, 1822, or, if BC, -750.</em><br>2. To also assist with improving date searching, please always add a date range:<br><em>e.g., if the display date is 1822, include Start date: 1822, End date: 1822.</em><br><br>NB: Date ranges for years prior to the change in calendar may need to be taken into account. <br>NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),  # noqa
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='start_date',
            field=authority.fields.PartialDateField(help_text='This element is used to identify the start date of the document(s). For Collection and Series levels, year dates should be used. For Sub-Series level and below, dates should include day and month (if known). Some approximation of date should always be possible from the record-relationship to other records in the series, office holders named, external events referred to, etc. <br><br>1. It is required that you follow the date format: <br><strong>(-)YYYY(-MM(-DD))</strong><br><em>e.g., 1822-03-27, 1822-03, 1822, or, if BC, -750.</em><br>2. To also assist with improving date searching, please always add a date range:<br><em>e.g., if the display date is 1822, include Start date: 1822, End date: 1822.</em><br><br>NB: Date ranges for years prior to the change in calendar may need to be taken into account. <br>NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),  # noqa
        ),
    ]
