# Generated by Django 2.2.13 on 2020-07-22 02:23

from django.db import migrations


def delete_language_data(apps, schema_editor):
    ArchivalRecord = apps.get_model('archival', 'ArchivalRecord')
    for record in ArchivalRecord.objects.all():
        for language in record.languages.all():
            record.languages.remove(language)
        record.language = None
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0107_auto_20200722_0321'),
    ]

    operations = [
        migrations.RunPython(delete_language_data),
    ]
