# Generated by Django 2.2.13 on 2020-07-22 02:27

import controlled_vocabulary.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0108_delete_old_languages_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='language',
            field=controlled_vocabulary.models.ControlledTermField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record_control_languages', to='controlled_vocabulary.ControlledTerm', verbose_name='Record language', vocabularies=['iso639-2']),  # noqa
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='language_new',
            field=controlled_vocabulary.models.ControlledTermField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='controlled_vocabulary.ControlledTerm', verbose_name='Record language', vocabularies=['iso639-2']),  # noqa
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='languages',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='This element is used to give the language(s) in which the documents are written. English is the default content for this field. A new Language field should be created for each language entered. Prominence should be reflected, with the most heavily-used language being given first. At collection and series level the Language data element should give an indication of the most prominent language rather than every single language.', related_name='_archivalrecord_languages_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['iso639-2']),  # noqa
        ),
    ]
