# Generated by Django 2.2.13 on 2020-07-22 02:08

from django.db import migrations


def migrate_language_data(apps, schema_editor):
    ArchivalRecord = apps.get_model('archival', 'ArchivalRecord')
    for record in ArchivalRecord.objects.all():
        for language in record.languages_new.all():
            record.languages.add(language)
        record.language = record.language_new
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0109_auto_20200722_0327'),
    ]

    operations = [
        migrations.RunPython(migrate_language_data),
    ]
