# Generated by Django 2.2.13 on 2020-07-22 02:34

import controlled_vocabulary.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0110_migrate_language_data_redux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalrecord',
            name='language_new',
        ),
        migrations.RemoveField(
            model_name='archivalrecord',
            name='languages_new',
        ),
        migrations.AlterField(
            model_name='archivalrecord',
            name='language',
            field=controlled_vocabulary.models.ControlledTermField(on_delete=django.db.models.deletion.PROTECT, related_name='record_control_languages', to='controlled_vocabulary.ControlledTerm', verbose_name='Record language', vocabularies=['iso639-2']),  # noqa
        ),
    ]
