# Generated by Django 2.2.13 on 2020-07-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0111_auto_20200722_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='references',
            field=models.ManyToManyField(blank=True, to='archival.Reference'),
        ),
    ]
