# Generated by Django 2.2.13 on 2020-08-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0112_ra_reference_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archival.Collection'),  # noqa
        ),
        migrations.AddField(
            model_name='item',
            name='parent_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archival.Collection'),  # noqa
        ),
    ]
