# Generated by Django 2.2.13 on 2020-08-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0113_auto_20200817_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrecord',
            name='calm_reference',
            field=models.CharField(blank=True, max_length=64, null=True,
                                   unique=True),
        ),
    ]
