# Generated by Django 2.2.13 on 2020-09-02 03:22

from django.db import migrations


def move_calm_references(apps, schema_editor):
    ArchivalRecord = apps.get_model('archival', 'ArchivalRecord')
    for record in ArchivalRecord.objects.all():
        try:
            ref = record.references.get(source__title='CALM')
        except Exception:
            continue
        record.calm_reference = ref.unitid
        record.save()
        ref.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0114_archivalrecord_calm_reference'),
    ]

    operations = [
        migrations.RunPython(move_calm_references),
    ]
