# Generated by Django 2.2.13 on 2020-10-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0116_auto_20200908_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='This field should only be used if there is information about the document(s) that cannot be accommodated in any of the other data elements.', null=True),
        ),
    ]
