# Generated by Django 2.2.13 on 2020-12-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0105_auto_20201029_1239'),
        ('archival', '0117_auto_20201029_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecord',
            name='provenance',
            field=models.TextField(blank=True, default='', help_text='This element is used to give information about the stewardship of papers prior to their accession to the Royal Archives. This data element should be used at whatever level it is appropriate to record custodial history information. Information on custodial history can often be found in the relevant accession record, but it is not always possible to ascertain how a collection entered the Royal Archives. If it is possible to ascertain that the collection entered the Royal Archives with the main deposit from Apsley House, this should be recorded. The name of donor and circumstances of the accession can be given, however it is not necessary to record the cost of the accession (at auction or otherwise). Information about Royal Household departments which reflect or affect the custodial history of the papers should also be included.', verbose_name='Custodial History/Provenance'),  # noqa
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('introduction', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('collections', models.ManyToManyField(blank=True, related_name='relating_group', to='archival.Collection')),  # noqa
                ('featured_entities', models.ManyToManyField(blank=True, related_name='featuring_group', to='authority.Entity')),  # noqa
                ('records', models.ManyToManyField(blank=True, related_name='featuring_group', to='archival.ArchivalRecord')),  # noqa
                ('related_entities', models.ManyToManyField(blank=True, related_name='relating_group', to='authority.Entity')),  # noqa
            ],
        ),
    ]
