# Generated by Django 2.2.13 on 2020-12-02 05:40

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0118_auto_20201202_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectgroup',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),  # noqa
        ),
        migrations.AddField(
            model_name='objectgroup',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),  # noqa
        ),
    ]
