# Generated by Django 2.2.13 on 2020-12-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0119_auto_20201202_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectgroup',
            name='records',
            field=models.ManyToManyField(blank=True, related_name='featuring_group', to='archival.ArchivalRecord', verbose_name='Featured archival records'),
        ),
        migrations.AlterField(
            model_name='objectgroup',
            name='slug',
            field=models.SlugField(verbose_name='URL slug'),
        ),
    ]
