# Generated by Django 2.2.13 on 2021-01-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0120_featured_records_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectgroup',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
