# Generated by Django 2.2.13 on 2021-03-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0121_objectgroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalrecordimage',
            name='order',
            field=models.CharField(max_length=64),
        ),
    ]
