# Generated by Django 2.0.9 on 2018-11-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name_plural': 'Identities'},
        ),
        migrations.AlterModelOptions(
            name='nameentry',
            options={'verbose_name_plural': 'Name entries'},
        ),
        migrations.RemoveField(
            model_name='identity',
            name='entity_type',
        ),
    ]
