# Generated by Django 2.0.9 on 2018-11-03 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_auto_remove_field_entity_type_from_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.EntityType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='identity',
            name='entity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='authority.Entity'),
            preserve_default=False,
        ),
    ]
