# Generated by Django 2.0.9 on 2018-11-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_create_model_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.RemoveField(
            model_name='nameentry',
            name='used_from',
        ),
        migrations.RemoveField(
            model_name='nameentry',
            name='used_to',
        ),
    ]
