# Generated by Django 2.0.9 on 2018-11-03 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0004_removed_date_fields_from_nameentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameentry',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameentry',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
