# Generated by Django 2.0.9 on 2018-11-05 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('script_codes', '0003_auto_20181103_1130'),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('authority', '0008_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_scripts', to='authority.Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='script_codes.Script')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
