# Generated by Django 2.0.9 on 2018-11-05 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0009_languagescript'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('abstract', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authority.Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('event', models.TextField()),
                ('place', models.CharField(max_length=256)),
                ('biography_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.BiographyHistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
