# Generated by Django 2.0.9 on 2018-11-05 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0010_biographyhistory_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=256)),
                ('notes', models.TextField()),
                ('citation', models.TextField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_descriptions', to='authority.Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='biographyhistory',
            options={'verbose_name': 'Biography/History', 'verbose_name_plural': 'Biography/History'},
        ),
    ]
