# Generated by Django 2.0.9 on 2018-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0014_legalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='structure_or_genealogy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
