# Generated by Django 2.0.9 on 2018-11-05 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0016_familytreelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('citation', models.TextField(blank=True, null=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='authority.Description')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.Entity')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authority.FamilyTreeLevel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
