# Generated by Django 2.0.9 on 2018-11-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0020_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='authority.Entity'),
        ),
    ]
