# Generated by Django 2.0.9 on 2018-11-06 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0021_alter_field_entity_on_relation_and_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authority.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
