# Generated by Django 2.0.9 on 2018-11-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('jargon', '0002_publicationstatus'),
        ('script_codes', '0003_change_meta_options_on_script'),
        ('authority', '0022_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='maintenance_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jargon.MaintenanceStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='publication_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jargon.PublicationStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='script',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='script_codes.Script'),
            preserve_default=False,
        ),
    ]
