# Generated by Django 2.0.9 on 2018-11-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0023_add_fields_to_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='rights_declaration',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
