# Generated by Django 2.0.9 on 2018-11-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0024_control_rights_declaration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name_plural': 'Control'},
        ),
    ]
