# Generated by Django 2.1.3 on 2018-11-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0026_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='entity_type',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
    ]
