# Generated by Django 2.1.3 on 2018-11-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0005_entitytype'),
        ('authority', '0027_delete_model_entitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jargon.EntityType'),
            preserve_default=False,
        ),
    ]
