# Generated by Django 2.1.3 on 2018-11-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0028_entity_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namepart',
            name='name_part_type',
        ),
        migrations.DeleteModel(
            name='NamePartType',
        ),
    ]
