# Generated by Django 2.1.3 on 2018-11-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0006_nameparttype'),
        ('authority', '0029_delete_model_nameparttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='namepart',
            name='name_part_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jargon.NamePartType'),
            preserve_default=False,
        ),
    ]
