# Generated by Django 2.1.3 on 2018-11-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0030_namepart_name_part_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='function',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
