# Generated by Django 2.1.3 on 2018-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0007_function'),
        ('authority', '0031_delete_model_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='function',
            field=models.ManyToManyField(to='jargon.Function'),
        ),
    ]
