# Generated by Django 2.1.3 on 2018-11-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0032_description_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='level',
        ),
        migrations.DeleteModel(
            name='FamilyTreeLevel',
        ),
    ]
