# Generated by Django 2.1.3 on 2018-11-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0008_familytreelevel'),
        ('authority', '0033_delete_model_familytreelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jargon.FamilyTreeLevel'),
            preserve_default=False,
        ),
    ]
