# Generated by Django 2.1.3 on 2018-11-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0034_structure_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='relation_type',
        ),
        migrations.DeleteModel(
            name='EntityRelationType',
        ),
    ]
