# Generated by Django 2.1.3 on 2018-11-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0009_entityrelationtype'),
        ('authority', '0035_delete_model_entityrelationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jargon.EntityRelationType'),
            preserve_default=False,
        ),
    ]
