# Generated by Django 2.1.3 on 2018-11-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0036_relation_relation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
