# Generated by Django 2.1.3 on 2018-11-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0010_resourcetype'),
        ('authority', '0037_delete_model_resourcetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jargon.ResourceType'),
            preserve_default=False,
        ),
    ]
