# Generated by Django 2.1.3 on 2018-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0038_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameentry',
            name='display_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
