# Generated by Django 2.1.3 on 2018-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0039_nameentry_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='preferred_identity',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
