# Generated by Django 2.1.3 on 2018-11-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('authority', '0040_identity_preferred_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place'),
        ),
    ]
