# Generated by Django 2.1.3 on 2018-11-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0042_rename_field_resource_type_on_resource_to_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='related_entity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_relations', to='authority.Entity'),
            preserve_default=False,
        ),
    ]
