# Generated by Django 2.1.4 on 2019-01-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0043_relation_related_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalstatus',
            options={'verbose_name_plural': 'Legal statuses'},
        ),
    ]
