# Generated by Django 2.1.4 on 2019-01-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0044_change_meta_options_on_legalstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalstatus',
            options={'verbose_name_plural': 'Legal status'},
        ),
    ]
