# Generated by Django 2.1.7 on 2019-03-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0045_change_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographyhistory',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography_history', to='authority.Description'),
        ),
    ]
