# Generated by Django 2.1.7 on 2019-04-26 10:51

from django.conf import settings
from django.db import migrations


def add_rights_declaration(apps, schema_editor):
    Control = apps.get_model('authority', 'Control')
    Entity = apps.get_model('authority', 'Entity')
    Language = apps.get_model('languages_plus', 'Language')
    MaintenanceStatus = apps.get_model('jargon', 'MaintenanceStatus')
    PublicationStatus = apps.get_model('jargon', 'PublicationStatus')
    Script = apps.get_model('script_codes', 'Script')

    language, _ = Language.objects.get_or_create(name_en='English')
    script, _ = Script.objects.get_or_create(name='Latin')

    for e in Entity.objects.all():
        try:
            _ = e.control
        except Control.DoesNotExist:
            e.control = Control()
            e.control.language = language
            e.control.script = script
            e.control.maintenance_status, _ = \
                MaintenanceStatus.objects.get_or_create(title='new')
            e.control.publication_status, _ = \
                PublicationStatus.objects.get_or_create(title='inprocess')
            e.control.save()

        if not e.control.rights_declaration:
            e.control.rights_declaration = \
                settings.AUTHORITY_RIGHTS_DECLARATION
            e.control.save()
            e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0047_alter_field_rights_declaration_on_control'),
    ]

    operations = [
        migrations.RunPython(add_rights_declaration,
                             reverse_code=migrations.RunPython.noop)
    ]
