# Generated by Django 2.1.7 on 2019-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0049_alter_field_rights_declaration_on_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='date_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='function',
            field=models.ManyToManyField(blank=True, to='jargon.Function'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='date_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='date_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='date_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='date_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='date_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='date_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='date_from',
            field=models.DateField(blank=True),
        ),
    ]
