# Generated by Django 2.1.7 on 2019-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0050_alter_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localdescription',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
