# Generated by Django 2.1.7 on 2019-04-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0051_alter_fields_citation_and_notes_on_localdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='level',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
