# Generated by Django 2.1.7 on 2019-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0052_delete_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='citation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
