# Generated by Django 2.1.7 on 2019-05-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0054_date_from_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='authority.Identity'),
        ),
        migrations.AddField(
            model_name='relation',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='authority.Identity'),
        ),
        migrations.AddField(
            model_name='resource',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='authority.Identity'),
        ),
    ]
