# Generated by Django 2.1.7 on 2019-05-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0057_remove_entity_rel'),
    ]
