# Generated by Django 2.1.7 on 2019-05-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0058_updating_event_relation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='source',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='authority.Control'),
        ),
    ]
