# Generated by Django 2.1.7 on 2019-06-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0057_add_project_slug'),
        ('authority', '0059_relation_name_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(help_text='Which project does this record                                    belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archival.Project'),
        ),
    ]
