# Generated by Django 2.1.7 on 2019-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0061_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
