# Generated by Django 2.1.7 on 2019-07-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0062_dates_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='display_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
