# Generated by Django 2.1.7 on 2019-07-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0063_sharc_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relation_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='related_entity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_relations', to='authority.Entity'),
        ),
    ]
