# Generated by Django 2.2.6 on 2019-10-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0066_plus_name_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Which project does this record                                    belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archival.Project'),
        ),
    ]
