# Generated by Django 2.2.7 on 2019-11-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0067_auto_20191015_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='structure_or_genealogy',
        ),
        migrations.AddField(
            model_name='biographyhistory',
            name='structure_or_genealogy',
            field=models.TextField(blank=True, help_text='This element &quot;encodes information within the description area, information expressing the internal administrative structure(s) of a corporate body and the dates of any changes to that structure that are significant to understanding the way that corporate body conducted affairs (such as dated organization charts), or the genealogy of a family (such as a family tree) in a way that demonstrates the interrelationships of its members with relevant dates&quot;. See structureOrGenealogy at eac.staatsbibliothek-berlin.de.', null=True),
        ),
        migrations.AlterField(
            model_name='biographyhistory',
            name='abstract',
            field=models.TextField(blank=True, help_text='If only a short biography is available, then it will be included in the abstract; if a long-form biography is available, then the abstract will contain a derived summary.', null=True),
        ),
        migrations.AlterField(
            model_name='biographyhistory',
            name='copyright',
            field=models.TextField(blank=True, help_text='Copyright statements for biographies or histories are to conform to the Creative Commons Licence used throughout the GPP - http://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-1.html.', null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='language',
            field=models.ForeignKey(help_text='This element denotes the language(s) used by an entity.', on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='description',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='languagescript',
            name='language',
            field=models.ForeignKey(help_text='This element denotes the language(s) used by an entity.', on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='citation',
            field=models.TextField(blank=True, help_text='This &quot;is a generic element available within a number of descriptive elements that cites an external resource in machine and / or human readable form&quot;. See citation at eac.staatsbibliothek-berlin.de.', null=True),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='gender',
            field=models.CharField(help_text='Note that gender relates to identity only and therefore should not be used to capture sexual preference (these are sometimes conflated). The term content should be taken from the Homosaurus. The most common terms likely to be used within the GPP are &quot;women&quot; and &quot;men&quot; but we need flexibility to include terms outside the binary. If the person did not live to adulthood it is acceptable to use &quot;girls&quot;, &quot;boys&quot;, or another term as appropriate.', max_length=256),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='language',
            field=models.ForeignKey(help_text='This element denotes the language(s) used by an entity.', on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='place',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='role',
            field=models.TextField(blank=True, help_text='For preference, for personal entities we should capture, at minimum, birth and death places. If it is considered useful, further places can be captured such as residences.', null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='relation_type',
            field=models.ForeignKey(help_text='This element &quot;contains the description of a resource related to the described entity&quot;. See resourceRelation at eac.staatsbibliothek-berlin.de.', on_delete=django.db.models.deletion.PROTECT, to='jargon.ResourceRelationType'),
        ),
    ]
