# Generated by Django 2.2.7 on 2019-11-28 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('authority', '0068_auto_20191127_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_from', models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True)),
                ('date_to', models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True)),
                ('display_date', models.CharField(blank=True, max_length=1024, null=True)),
                ('event', models.TextField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='authority.Description')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
