# Generated by Django 2.2.7 on 2019-11-28 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('authority', '0068_auto_20191127_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='biography_history',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='authority.Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place'),
        ),
    ]
