# Generated by Django 2.2.7 on 2019-11-28 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0020_delete_familytreelevel'),
        ('authority', '0069_event_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographyhistory',
            name='abstract',
            field=models.TextField(help_text='If only a short biography is available, then it will be included in the abstract; if a long-form biography is available, then the abstract will contain a derived summary.', null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='language',
            field=models.ForeignKey(blank=True, help_text='This element denotes the language(s) used by an entity.', on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='control',
            name='script',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='script_codes.Script'),
        ),
        migrations.AlterField(
            model_name='languagescript',
            name='language',
            field=models.ForeignKey(blank=True, help_text='This element denotes the language(s) used by an entity.', on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='languagescript',
            name='script',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='script_codes.Script'),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Descriptive notes'),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='language',
            field=models.ForeignKey(blank=True, help_text='This element denotes the language(s) used by an entity.', on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='script',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='script_codes.Script'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='role',
            field=models.TextField(help_text='For preference, for personal entities we should capture, at minimum, birth and death places. If it is considered useful, further places can be captured such as residences.', null=True),
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_from', models.DateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.', null=True)),
                ('date_to', models.DateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.', null=True)),
                ('display_date', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='authority.Description')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jargon.Function')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
