# Generated by Django 2.2.7 on 2019-11-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0070_function_requiredFieldAlterations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='related_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_relations', to='authority.Entity'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
