# Generated by Django 2.2.7 on 2019-11-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0071_entities_requiredFields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jargon.Function', verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptive Notes'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptive Notes'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place', verbose_name='Place related to relationship'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='related_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_relations', to='authority.Entity', verbose_name='Related person or corporate body'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_detail',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jargon.EntityRelationType', verbose_name='Relationship type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='relation_type',
            field=models.ForeignKey(help_text='This element &quot;contains the description of a resource related to the described entity&quot;. See resourceRelation at eac.staatsbibliothek-berlin.de.', on_delete=django.db.models.deletion.PROTECT, to='jargon.ResourceRelationType', verbose_name='Resource relationship type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
