# Generated by Django 2.2.7 on 2020-01-14 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0072_verbose_names_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Which project does this record belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archival.Project'),
        ),
    ]
