# Generated by Django 2.2.5 on 2020-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0074_auto_20200220_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
