# Generated by Django 2.2.5 on 2020-03-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0075_entity_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='function',
        ),
    ]
