# Generated by Django 2.2.5 on 2020-03-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0076_remove_description_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_deleted',
        ),
    ]
