# Generated by Django 2.2.5 on 2020-03-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0077_remove_entity_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameentry',
            name='is_royal_name',
            field=models.BooleanField(default=False),
        ),
    ]
