# Generated by Django 2.2.5 on 2020-04-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0078_nameentry_is_royal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='notes',
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='gender',
            field=models.ForeignKey(help_text='Note that gender relates to identity only and therefore should not be used to capture sexual preference (these are sometimes conflated). The term content should be taken from the Homosaurus. The most common terms likely to be used within the GPP are &quot;women&quot; and &quot;men&quot; but we need flexibility to include terms outside the binary. If the person did not live to adulthood it is acceptable to use &quot;girls&quot;, &quot;boys&quot;, or another term as appropriate.', on_delete=django.db.models.deletion.CASCADE, to='jargon.Gender'),
        ),
    ]
