# Generated by Django 2.2.12 on 2020-05-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0079_auto_20200422_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
