# Generated by Django 2.2.12 on 2020-06-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0080_auto_20200508_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographyhistory',
            name='abstract',
            field=models.TextField(default='', help_text='If only a short biography is available, then it will be included in the abstract; if a long-form biography is available, then the abstract will contain a derived summary.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biographyhistory',
            name='content',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biographyhistory',
            name='copyright',
            field=models.TextField(blank=True, default='', help_text='Copyright statements for biographies or histories are to conform to the Creative Commons Licence used throughout the GPP - http://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-1.html.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biographyhistory',
            name='sources',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biographyhistory',
            name='structure_or_genealogy',
            field=models.TextField(blank=True, default='', help_text='This element &quot;encodes information within the description area, information expressing the internal administrative structure(s) of a corporate body and the dates of any changes to that structure that are significant to understanding the way that corporate body conducted affairs (such as dated organization charts), or the genealogy of a family (such as a family tree) in a way that demonstrates the interrelationships of its members with relevant dates&quot;. See structureOrGenealogy at eac.staatsbibliothek-berlin.de.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='function',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identity',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='citation',
            field=models.TextField(blank=True, default='', help_text='This &quot;is a generic element available within a number of descriptive elements that cites an external resource in machine and / or human readable form&quot;. See citation at eac.staatsbibliothek-berlin.de.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Descriptive Notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mandate',
            name='citation',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mandate',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mandate',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Descriptive Notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='role',
            field=models.TextField(blank=True, default='', help_text='For preference, for personal entities we should capture, at minimum, birth and death places. If it is considered useful, further places can be captured such as residences.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relation',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_detail',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='source',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
