# Generated by Django 2.2.12 on 2020-06-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0081_auto_20200601_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographyhistory',
            name='copyright',
            field=models.TextField(blank=True, help_text='Copyright statements included here relate to a person&rsquo;s or corporate body&rsquo;s biography/history only. Include Creative Commons Licences where these govern reproduction of the material included. If the biography/history is original work in which you wish to assert copyright or include a Creative Commons Licence please contact our GPP academic leads, Arthur Burns or Karin Wulf for more information.'),
        ),
        migrations.AlterField(
            model_name='biographyhistory',
            name='sources',
            field=models.TextField(blank=True, help_text='Format citations using the Chicago Style guide - http://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-1.html.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(verbose_name='Source'),
        ),
    ]
