# Generated by Django 2.2.12 on 2020-06-04 22:45

import authority.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0082_auto_20200601_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='description',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='entity',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='entity',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='function',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='function',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='identity',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='identity',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='localdescription',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='localdescription',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='nameentry',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='nameentry',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='place',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='place',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
        migrations.AddField(
            model_name='relation',
            name='date_from_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A birth date, or for corporate bodies, a creation date.'),
        ),
        migrations.AddField(
            model_name='relation',
            name='date_to_partial',
            field=authority.fields.PartialDateField(blank=True, help_text='Date of existence. A death date, or for corporate bodies, an extinction date.'),
        ),
    ]
