# Generated by Django 2.2.12 on 2020-06-04 22:45

from django.db import migrations


def date_to_iso_string(apps, schema_editor):
    # We can't import the models directly as each may be a newer
    # version than this migration expects. We use the historical
    # version.
    models = (
        'Description', 'Entity', 'Event', 'Function', 'Identity',
        'LegalStatus', 'LocalDescription', 'Mandate', 'NameEntry',
        'Place', 'Relation'
    )
    for model_name in models:
        model = apps.get_model('authority', model_name)
        for obj in model.objects.all():
            if obj.date_from:
                obj.date_from_partial = obj.date_from.isoformat()
            if obj.date_to:
                obj.date_to_partial = obj.date_to.isoformat()
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0083_auto_20200604_2345'),
    ]

    operations = [
        migrations.RunPython(date_to_iso_string),
    ]
