# Generated by Django 2.2.12 on 2020-06-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0084_date_field_to_date_field_partial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='description',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='function',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='function',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='legalstatus',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='legalstatus',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='localdescription',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='localdescription',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='nameentry',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='nameentry',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='place',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='date_to',
        ),
    ]
