# Generated by Django 2.2.12 on 2020-06-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0086_auto_20200605_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, max_length=512, verbose_name='URL'),
        ),
    ]
