# Generated by Django 2.2.12 on 2020-06-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0088_remove_biographyhistory_structure_or_genealogy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place'),
        ),
    ]
