# Generated by Django 2.2.12 on 2020-06-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0092_auto_20200615_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='rights_declaration_citation',
            field=models.URLField(blank=True, default='https://creativecommons.org/publicdomain/zero/1.0/'),
        ),
    ]
