# Generated by Django 2.2.12 on 2020-06-18 12:15

import authority.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0093_auto_20200616_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographyhistory',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biographyhistory',
            name='sources',
            field=models.TextField(blank=True, help_text='Format citations using the Chicago Style guide - http://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-1.html.'),
        ),
        migrations.AlterField(
            model_name='description',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='description',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='function',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='function',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='localdescription',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='place',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='place',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='date_from',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='date_to',
            field=authority.fields.PartialDateField(blank=True, help_text='To assist with improving date searching please always add a date range - for example, if the display date is 1822, include date range start 01/01/1822, end 31/12/1822. NB. Date ranges for years prior to the change in calendar may need to be taken into account. NB: For dates spanning the change in calendars from Julian to Gregorian in many European countries and their colonies, include New Style dates for machine-reading. Old Style dates can be included in the display date field where needed.'),
        ),
    ]
