# Generated by Django 2.2.12 on 2020-06-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0094_auto_20200618_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='role',
            field=models.CharField(blank=True, help_text='For preference, for personal entities we should capture, at minimum, birth and death places. If it is considered useful, further places can be captured such as residences.', max_length=256),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_detail',
            field=models.TextField(help_text='This field describes the relationship between the related person or corporate body and the person or corporate body in question, e.g. Charlotte is the wife of George III.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='relation_type',
            field=models.ForeignKey(help_text='This field defines the relationship between a resource and the person or corporate body in question. See resourceRelation at eac.staatsbibliothek-berlin.de for more information.', on_delete=django.db.models.deletion.PROTECT, to='jargon.ResourceRelationType', verbose_name='Resource relationship type'),
        ),
    ]
