# Generated by Django 2.2.13 on 2020-07-22 00:36

import controlled_vocabulary.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('authority', '0096_auto_20200713_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='language_new',
            field=controlled_vocabulary.models.ControlledTermField(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='controlled_vocabulary.ControlledTerm', verbose_name='Record language', vocabularies=['iso639-2']),  # noqa
        ),
        migrations.AddField(
            model_name='languagescript',
            name='language_new',
            field=controlled_vocabulary.models.ControlledTermField(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['iso639-2']),  # noqa
        ),
        migrations.AddField(
            model_name='nameentry',
            name='language_new',
            field=controlled_vocabulary.models.ControlledTermField(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['iso639-2']),  # noqa
        ),
    ]
