# Generated by Django 2.2.13 on 2020-07-22 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0097_auto_20200722_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='language',
            field=models.ForeignKey(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language', verbose_name='Record language'),  # noqa
        ),
        migrations.AlterField(
            model_name='languagescript',
            name='language',
            field=models.ForeignKey(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),  # noqa
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='language',
            field=models.ForeignKey(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),  # noqa
        ),
    ]
