# Generated by Django 2.2.13 on 2020-07-22 03:16

from django.db import migrations
from django.db.models import Q

from controlled_vocabulary.apps import ControlledVocabularyConfig


def search_term_or_none(ControlledVocabulary, ControlledTerm, prefix, pattern,
                        exact=False):
    '''Returns a `ControlledTerm` for the `ControlledVocabulary` with the
    given `prefix` and `pattern`.

    It searches in the external vocabulary and returns the first matching term
    If exact is True it will return None if the exact pattern is not found.
    It also saves the term in the database if it doesn't already exists.

    Returns None if no vocabulary with that prefix is found.
    Returns None if the pattern is None or empty.
    '''
    ret = None

    if prefix and pattern:
        try:
            ret = search_term(ControlledVocabulary, ControlledTerm, prefix,
                              pattern, exact=exact)
        except ControlledVocabulary.DoesNotExist:
            pass

    return ret


def search_term(ControlledVocabulary, ControlledTerm, prefix, pattern,
                exact=False):
    """Returns a `ControlledTerm` for the `ControlledVocabulary` with the
    given `prefix` and `pattern`.

    It first searches for an exact match in the DB (ControlledTerm).
    It then searches in the external vocabulary
        and returns the first matching term.
    If exact is True it will return None if the first found term is not an
        exact match of pattern.
    It also saves the term in the database if it doesn't already exists.

    Throws an exception if no vocabulary with that prefix is found.
    """

    ret = None

    # try the DB first
    ret = ControlledTerm.objects.filter(
        Q(termid__iexact=pattern) | Q(label__iexact=pattern),
        vocabulary__prefix=prefix
    ).first()
    if ret:
        return ret

    # external search
    cv = ControlledVocabulary.objects.get(prefix=prefix)
    manager = ControlledVocabularyConfig.get_vocabulary_manager(cv.prefix)

    terms = manager.search(pattern)

    if terms:
        term = terms[0]

        if (not exact
            or (term[1].lower() == pattern.lower())
                or (term[0].lower() == pattern.lower())):
            desc = term[2] if len(term) > 2 else ''
            ret, _ = ControlledTerm.objects.get_or_create(
                vocabulary=cv, termid=term[0].strip(),
                defaults={'label': term[1], 'description': desc}
            )

    return ret


def lookup_language(ControlledVocabulary, ControlledTerm, language):
    """Return the ControlledTerm object corresponding to the
    languages_plus `language`."""
    lang = search_term_or_none(ControlledVocabulary, ControlledTerm,
                               'iso639-2', language.iso_639_2T)
    if lang is None:
        lang = search_term_or_none(ControlledVocabulary, ControlledTerm,
                                   'iso639-2', language.iso_639_2B)
        if lang is None:
            raise Exception(
                'Missing controlled_vocabulary language data: could not find '
                'language matching "{}" or "{}"'.format(
                    language.iso_639_2T, language.iso_639_2B))
    return lang


def migrate_language_data(apps, schema_editor):
    Control = apps.get_model('authority', 'Control')
    ControlledTerm = apps.get_model('controlled_vocabulary', 'ControlledTerm')
    ControlledVocabulary = apps.get_model('controlled_vocabulary',
                                          'ControlledVocabulary')
    LanguageScript = apps.get_model('authority', 'LanguageScript')
    NameEntry = apps.get_model('authority', 'NameEntry')
    for control in Control.objects.all():
        control.language_new = lookup_language(
            ControlledVocabulary, ControlledTerm, control.language)
        control.language = None
        control.save()
    for language_script in LanguageScript.objects.all():
        language_script.language_new = lookup_language(
            ControlledVocabulary, ControlledTerm, language_script.language)
        language_script.language = None
        language_script.save()
    for name_entry in NameEntry.objects.all():
        name_entry.language_new = lookup_language(
            ControlledVocabulary, ControlledTerm, name_entry.language)
        name_entry.language = None
        name_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0098_auto_20200722_0415'),
    ]

    operations = [
        migrations.RunPython(migrate_language_data),
    ]
