# Generated by Django 2.2.13 on 2020-07-22 03:34

import controlled_vocabulary.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0099_migrate_language_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='language',
            field=controlled_vocabulary.models.ControlledTermField(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='controlled_vocabulary.ControlledTerm', verbose_name='Record language', vocabularies=['iso639-2']),  # noqa
        ),
        migrations.AlterField(
            model_name='languagescript',
            name='language',
            field=controlled_vocabulary.models.ControlledTermField(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['iso639-2']),  # noqa
        ),
        migrations.AlterField(
            model_name='nameentry',
            name='language',
            field=controlled_vocabulary.models.ControlledTermField(blank=True, help_text='This element denotes the language(s) used by an entity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['iso639-2']),  # noqa
        ),
    ]
