# Generated by Django 2.2.13 on 2020-07-22 03:27

from django.db import migrations


def migrate_language_data(apps, schema_editor):
    Control = apps.get_model('authority', 'Control')
    LanguageScript = apps.get_model('authority', 'LanguageScript')
    NameEntry = apps.get_model('authority', 'NameEntry')
    for control in Control.objects.all():
        control.language = control.language_new
        control.save()
    for language_script in LanguageScript.objects.all():
        language_script.language = language_script.language_new
        language_script.save()
    for name_entry in NameEntry.objects.all():
        name_entry.language = name_entry.language_new
        name_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0100_auto_20200722_0434'),
    ]

    operations = [
        migrations.RunPython(migrate_language_data),
    ]
