# Generated by Django 2.2.13 on 2020-08-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0102_auto_20200722_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='not_duplicates',
            field=models.ManyToManyField(related_name='_entity_not_duplicates_+', to='authority.Entity'),  # noqa
        ),
    ]
