# Generated by Django 2.2.13 on 2020-08-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0103_entity_not_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='not_duplicates',
            field=models.ManyToManyField(blank=True, related_name='_entity_not_duplicates_+', to='authority.Entity'),
        ),
    ]
