# Generated by Django 2.1.3 on 2018-11-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0010_resourcetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityrelationtype',
            options={'verbose_name': 'EAC: Entity relation type'},
        ),
        migrations.AlterModelOptions(
            name='entitytype',
            options={'verbose_name': 'EAC: Entity type'},
        ),
        migrations.AlterModelOptions(
            name='familytreelevel',
            options={'verbose_name': 'EAC: Family tree level'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'EAC: Function'},
        ),
        migrations.AlterModelOptions(
            name='maintenancestatus',
            options={'verbose_name': 'EAC: Name authority file status', 'verbose_name_plural': 'EAC: Name authority file statuses'},
        ),
        migrations.AlterModelOptions(
            name='nameparttype',
            options={'verbose_name': 'EAC: Name part type'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'EAD: Publication'},
        ),
        migrations.AlterModelOptions(
            name='publicationstatus',
            options={'verbose_name_plural': 'EAC/EAD: Publication status'},
        ),
        migrations.AlterModelOptions(
            name='recordtype',
            options={'verbose_name_plural': 'EAD: Record type'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name_plural': 'EAD: Resource type'},
        ),
    ]
