# Generated by Django 2.1.3 on 2018-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0011_change_meta_option_on_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationstatus',
            name='is_archival',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publicationstatus',
            name='is_authority',
            field=models.BooleanField(default=True),
        ),
    ]
