# Generated by Django 2.1.3 on 2018-11-29 11:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('authority', '0042_rename_field_resource_type_on_resource_to_relation_type'),
        ('jargon', '0012_add_fields_is_archival_and_is_authority_to_publicationstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceType',
            new_name='ResourceRelationType',
        ),
        migrations.AlterModelOptions(
            name='resourcerelationtype',
            options={'verbose_name_plural': 'EAC: Resource relation type'},
        ),
    ]
