# Generated by Django 2.1.3 on 2018-12-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0015_alter_unique_together_for_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'EAD: Repository', 'verbose_name_plural': 'EAD: Repositories'},
        ),
    ]
