# Generated by Django 2.1.4 on 2019-01-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0017_referencesource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancestatus',
            options={'verbose_name': 'EAC: Name authority file status', 'verbose_name_plural': 'EAC: Name authority file status'},
        ),
        migrations.AlterModelOptions(
            name='nameparttype',
            options={'verbose_name': 'EAC: Name part type', 'verbose_name_plural': 'EAC: Name part types'},
        ),
        migrations.AlterModelOptions(
            name='recordtype',
            options={'verbose_name_plural': 'EAD: Record types'},
        ),
        migrations.AlterModelOptions(
            name='resourcerelationtype',
            options={'verbose_name_plural': 'EAC: Resource relation types'},
        ),
    ]
