# Generated by Django 2.1.7 on 2019-02-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0018_change_meta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordtype',
            options={'verbose_name': 'EAD: Record type',
                     'verbose_name_plural': 'EAD: Record types'},
        ),
    ]
