# Generated by Django 2.1.7 on 2019-04-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0052_delete_structure'),
        ('jargon', '0019_change_recordtype_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyTreeLevel',
        ),
    ]
