# Generated by Django 2.2.5 on 2020-02-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0020_delete_familytreelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameparttype',
            name='entity_type',
            field=models.CharField(choices=[('CB', 'Corporate Body'), ('PE', 'Person')], default='PE', max_length=2),
        ),
    ]
