# Generated by Django 2.2.5 on 2020-03-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0022_collaborativeworkspaceeditortype_editingeventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='alt_labels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='function',
            name='broader',
            field=models.ManyToManyField(blank=True, related_name='narrower', to='jargon.Function'),
        ),
        migrations.AddField(
            model_name='function',
            name='is_term',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='function',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='reverse_related', to='jargon.Function'),
        ),
        migrations.AddField(
            model_name='function',
            name='schemes',
            field=models.ManyToManyField(blank=True, related_name='in_scheme', to='jargon.Function'),
        ),
    ]
