# Generated by Django 2.2.5 on 2020-04-22 00:44

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0023_auto_20200317_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('alt_labels', models.TextField(blank=True)),
                ('uri', models.URLField(blank=True)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='jargon.GenderTerms')),
                ('related', models.ManyToManyField(blank=True, related_name='reverse_related', to='jargon.GenderTerms')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
