# Generated by Django 2.2.5 on 2020-04-22 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0024_genderterms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenderTerms',
            new_name='GenderTerm',
        ),
    ]
