# Generated by Django 2.2.5 on 2020-04-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0025_auto_20200422_0328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenderTerm',
            new_name='Gender',
        ),
    ]
